Our Hypothesis is, as a result of the digital exposure control on the SBIG AllSky-340, that the integration / exposure time alone will not be sufficient to draw conclusions.

In [1]:
import os
from glob import glob
import pandas as pd

files = sorted(
    glob(os.path.join(os.getcwd(), '../..' , 'data', '2010-*.parquet')) +
    glob(os.path.join(os.getcwd(), '../..' , 'data', '2011-*.parquet')) +
    glob(os.path.join(os.getcwd(), '../..' , 'data', '2012-*.parquet')) +
    # 2013 Data is missing
    glob(os.path.join(os.getcwd(), '../..' , 'data', '2014-*.parquet')) +
    glob(os.path.join(os.getcwd(), '../..' , 'data', '2015-*.parquet'))
    # Post 2015 data is pending antialias parsing
)
files

['/home/rainybyte/DataspellProjects/allsky-light-pollution/notebooks/exploratory/../../data/2010-08.parquet',
 '/home/rainybyte/DataspellProjects/allsky-light-pollution/notebooks/exploratory/../../data/2010-09.parquet',
 '/home/rainybyte/DataspellProjects/allsky-light-pollution/notebooks/exploratory/../../data/2010-10.parquet',
 '/home/rainybyte/DataspellProjects/allsky-light-pollution/notebooks/exploratory/../../data/2010-11.parquet',
 '/home/rainybyte/DataspellProjects/allsky-light-pollution/notebooks/exploratory/../../data/2010-12.parquet',
 '/home/rainybyte/DataspellProjects/allsky-light-pollution/notebooks/exploratory/../../data/2011-01.parquet',
 '/home/rainybyte/DataspellProjects/allsky-light-pollution/notebooks/exploratory/../../data/2011-02.parquet',
 '/home/rainybyte/DataspellProjects/allsky-light-pollution/notebooks/exploratory/../../data/2011-03.parquet',
 '/home/rainybyte/DataspellProjects/allsky-light-pollution/notebooks/exploratory/../../data/2011-04.parquet',
 '/home/rainybyte/DataspellProjects/allsky-light-pollution/notebooks/exploratory/../../data/2011-05.parquet',
 '/home/rainybyte/DataspellProjects/allsky-light-pollution/notebooks/exploratory/../../data/2011-06.parquet',
 '/home/rainybyte/DataspellProjects/allsky-light-pollution/notebooks/exploratory/../../data/2011-07.parquet',
 '/home/rainybyte/DataspellProjects/allsky-light-pollution/notebooks/exploratory/../../data/2011-08.parquet',
 '/home/rainybyte/DataspellProjects/allsky-light-pollution/notebooks/exploratory/../../data/2011-09.parquet',
 '/home/rainybyte/DataspellProjects/allsky-light-pollution/notebooks/exploratory/../../data/2011-10.parquet',
 '/home/rainybyte/DataspellProjects/allsky-light-pollution/notebooks/exploratory/../../data/2011-11.parquet',
 '/home/rainybyte/DataspellProjects/allsky-light-pollution/notebooks/exploratory/../../data/2011-12.parquet',
 '/home/rainybyte/DataspellProjects/allsky-light-pollution/notebooks/exploratory/../../data/2012-01.parquet',
 '/home/rainybyte/DataspellProjects/allsky-light-pollution/notebooks/exploratory/../../data/2012-02.parquet',
 '/home/rainybyte/DataspellProjects/allsky-light-pollution/notebooks/exploratory/../../data/2012-03.parquet',
 '/home/rainybyte/DataspellProjects/allsky-light-pollution/notebooks/exploratory/../../data/2012-04.parquet',
 '/home/rainybyte/DataspellProjects/allsky-light-pollution/notebooks/exploratory/../../data/2012-05.parquet',
 '/home/rainybyte/DataspellProjects/allsky-light-pollution/notebooks/exploratory/../../data/2012-06.parquet',
 '/home/rainybyte/DataspellProjects/allsky-light-pollution/notebooks/exploratory/../../data/2012-07.parquet',
 '/home/rainybyte/DataspellProjects/allsky-light-pollution/notebooks/exploratory/../../data/2012-08.parquet',
 '/home/rainybyte/DataspellProjects/allsky-light-pollution/notebooks/exploratory/../../data/2012-09.parquet',
 '/home/rainybyte/DataspellProjects/allsky-light-pollution/notebooks/exploratory/../../data/2012-10.parquet',
 '/home/rainybyte/DataspellProjects/allsky-light-pollution/notebooks/exploratory/../../data/2012-11.parquet',
 '/home/rainybyte/DataspellProjects/allsky-light-pollution/notebooks/exploratory/../../data/2012-12.parquet',
 '/home/rainybyte/DataspellProjects/allsky-light-pollution/notebooks/exploratory/../../data/2014-01.parquet',
 '/home/rainybyte/DataspellProjects/allsky-light-pollution/notebooks/exploratory/../../data/2014-02.parquet',
 '/home/rainybyte/DataspellProjects/allsky-light-pollution/notebooks/exploratory/../../data/2014-03.parquet',
 '/home/rainybyte/DataspellProjects/allsky-light-pollution/notebooks/exploratory/../../data/2014-04.parquet',
 '/home/rainybyte/DataspellProjects/allsky-light-pollution/notebooks/exploratory/../../data/2014-05.parquet',
 '/home/rainybyte/DataspellProjects/allsky-light-pollution/notebooks/exploratory/../../data/2014-07.parquet',
 '/home/rainybyte/DataspellProjects/allsky-light-pollution/notebooks/exploratory/../../data/2014-08.parquet',
 '/home/rainybyte/DataspellProjects/allsky-light-pollution/notebooks/exploratory/../../data/2014-09.parquet',
 '/home/rainybyte/DataspellProjects/allsky-light-pollution/notebooks/exploratory/../../data/2014-10.parquet',
 '/home/rainybyte/DataspellProjects/allsky-light-pollution/notebooks/exploratory/../../data/2014-11.parquet',
 '/home/rainybyte/DataspellProjects/allsky-light-pollution/notebooks/exploratory/../../data/2014-12.parquet',
 '/home/rainybyte/DataspellProjects/allsky-light-pollution/notebooks/exploratory/../../data/2015-01.parquet',
 '/home/rainybyte/DataspellProjects/allsky-light-pollution/notebooks/exploratory/../../data/2015-02.parquet',
 '/home/rainybyte/DataspellProjects/allsky-light-pollution/notebooks/exploratory/../../data/2015-03.parquet',
 '/home/rainybyte/DataspellProjects/allsky-light-pollution/notebooks/exploratory/../../data/2015-04.parquet',
 '/home/rainybyte/DataspellProjects/allsky-light-pollution/notebooks/exploratory/../../data/2015-05.parquet',
 '/home/rainybyte/DataspellProjects/allsky-light-pollution/notebooks/exploratory/../../data/2015-06.parquet',
 '/home/rainybyte/DataspellProjects/allsky-light-pollution/notebooks/exploratory/../../data/2015-07.parquet',
 '/home/rainybyte/DataspellProjects/allsky-light-pollution/notebooks/exploratory/../../data/2015-08.parquet',
 '/home/rainybyte/DataspellProjects/allsky-light-pollution/notebooks/exploratory/../../data/2015-09.parquet',
 '/home/rainybyte/DataspellProjects/allsky-light-pollution/notebooks/exploratory/../../data/2015-10.parquet',
 '/home/rainybyte/DataspellProjects/allsky-light-pollution/notebooks/exploratory/../../data/2015-11.parquet',
 '/home/rainybyte/DataspellProjects/allsky-light-pollution/notebooks/exploratory/../../data/2015-12.parquet']

In [2]:
from dask import dataframe as dd
df: dd.DataFrame = dd.read_parquet(files)
df.describe

<bound method DataFrame.describe of Dask DataFrame Structure:
                  date    time exposure filename
npartitions=52
                string  string   string   string
                   ...     ...      ...      ...
...                ...     ...      ...      ...
                   ...     ...      ...      ...
                   ...     ...      ...      ...
Dask Name: read_parquet, 1 expression
Expr=ReadParquetFSSpec(e5a90d7)>

In [3]:
df.compute()

          date      time exposure   filename
0   2010/08/11  19:16:0?   0.0000  000021138
1   2010/08/11  19:17:09   0.0000  000021139
2   2010/08/11  19:24:05   0.0000  000021140
3   2010/08/11  19:25:05   0.0000  000021141
4   2010/08/11  19:26:05   0.0000  000021142
..         ...       ...      ...        ...
21  2015/12/31  23:43:24   3.0188  000940779
22  2015/12/31  23:46:02   3.0188  000940780
23  2015/12/31  23:49:46   3.0188  000940781
24  2015/12/31  23:52:28   3.0188  000940782
25  2015/12/31  23:54:17   3.0188  000940783

[647738 rows x 4 columns]

In [4]:
from allsky.validation import is_valid_record_series

invalid_rows = ~is_valid_record_series(df)
df[invalid_rows].compute()

          date      time exposure   filename
0   2010/08/11  19:16:0?   0.0000  000021138
28  2010/0?/13  19:16:0?   0.0000  000021486
5   2010/08/1?  19:29:18   0.0000  000021495
13  ???0/08/?5  2?:36:16   0.0011  000022367
12  2010/0?/16  19:23:4?   0.0000  000022718
..         ...       ...      ...        ...
23  2015/11/23  14:08:17   0.0000  000926?01
24  2015/11/23  14:09:17   0.0000  000926?02
25  2015/11/23  14:10:40   0.0000  000926?03
27  2015/11/23  14:13:03   0.0000  000926?05
28  2015/11/23  14:14:03   0.0000  0009264?6

[4528 rows x 4 columns]

In [5]:
df[~invalid_rows].compute()

          date      time exposure   filename
1   2010/08/11  19:17:09   0.0000  000021139
2   2010/08/11  19:24:05   0.0000  000021140
3   2010/08/11  19:25:05   0.0000  000021141
4   2010/08/11  19:26:05   0.0000  000021142
5   2010/08/11  19:27:06   0.0000  000021143
..         ...       ...      ...        ...
21  2015/12/31  23:43:24   3.0188  000940779
22  2015/12/31  23:46:02   3.0188  000940780
23  2015/12/31  23:49:46   3.0188  000940781
24  2015/12/31  23:52:28   3.0188  000940782
25  2015/12/31  23:54:17   3.0188  000940783

[643210 rows x 4 columns]