In [10]:
import pandas as pd
import numpy as np
import dask.dataframe as dd
import matplotlib.pyplot as plt
import os
from glob import glob
from dask.array.image import imread
# image_location = "/data/jfreuden/SomeSkyImages/"
# enriched_df_location = "/data/jfreuden/allsky-light-pollution-simple/data/enriched.parquet"
image_location = "/home/rainybyte/SomeSkyImages/"
enriched_df_location = "../../data/enriched_df.parquet"
enriched_df = pd.read_parquet(enriched_df_location)
enriched_df

,date,time,exposure,filename,source_file,timestamp,image_paths,image_mean,image_sum,image_min,image_max
8,2010/08/11,22:38:00,2.7883,000021274,2010-08.parquet,2010-08-11 22:38:00,/home/rainybyte/SomeSkyImages/2010-08/AllSkyIm...,157.789822,19822662,105,242
9,2010/08/11,22:39:17,2.4769,000021275,2010-08.parquet,2010-08-11 22:39:17,/home/rainybyte/SomeSkyImages/2010-08/AllSkyIm...,159.858382,20082529,102,242
10,2010/08/11,22:40:17,2.4769,000021276,2010-08.parquet,2010-08-11 22:40:17,/home/rainybyte/SomeSkyImages/2010-08/AllSkyIm...,163.385713,20525657,115,240
11,2010/08/11,22:41:34,2.4769,000021277,2010-08.parquet,2010-08-11 22:41:34,/home/rainybyte/SomeSkyImages/2010-08/AllSkyIm...,166.985608,20977901,117,245
12,2010/08/11,22:42:34,2.4769,000021278,2010-08.parquet,2010-08-11 22:42:34,/home/rainybyte/SomeSkyImages/2010-08/AllSkyIm...,158.146314,19867447,99,248
...,...,...,...,...,...,...,...,...,...,...,...
4,2026/03/25,05:40:08,32.0241,000422467,2026-03.parquet,2026-03-25 05:40:08,/home/rainybyte/SomeSkyImages/2026-03/AllSkyIm...,103.790141,13038844,51,221
5,2026/03/25,05:40:41,32.0241,000422468,2026-03.parquet,2026-03-25 05:40:41,/home/rainybyte/SomeSkyImages/2026-03/AllSkyIm...,103.978412,13062496,57,235
6,2026/03/25,05:41:34,36.3559,000422469,2026-03.parquet,2026-03-25 05:41:34,/home/rainybyte/SomeSkyImages/2026-03/AllSkyIm...,107.699698,13529990,56,232
7,2026/03/25,05:42:11,36.3559,000422470,2026-03.parquet,2026-03-25 05:42:11,/home/rainybyte/SomeSkyImages/2026-03/AllSkyIm...,107.371680,13488782,59,253
8,2026/03/25,05:42:49,36.3559,000422471,2026-03.parquet,2026-03-25 05:42:49,/home/rainybyte/SomeSkyImages/2026-03/AllSkyIm...,107.022416,13444905,53,248

In [11]:
enriched_df

,date,time,exposure,filename,source_file,timestamp,image_paths,image_mean,image_sum,image_min,image_max
8,2010/08/11,22:38:00,2.7883,000021274,2010-08.parquet,2010-08-11 22:38:00,/home/rainybyte/SomeSkyImages/2010-08/AllSkyIm...,157.789822,19822662,105,242
9,2010/08/11,22:39:17,2.4769,000021275,2010-08.parquet,2010-08-11 22:39:17,/home/rainybyte/SomeSkyImages/2010-08/AllSkyIm...,159.858382,20082529,102,242
10,2010/08/11,22:40:17,2.4769,000021276,2010-08.parquet,2010-08-11 22:40:17,/home/rainybyte/SomeSkyImages/2010-08/AllSkyIm...,163.385713,20525657,115,240
11,2010/08/11,22:41:34,2.4769,000021277,2010-08.parquet,2010-08-11 22:41:34,/home/rainybyte/SomeSkyImages/2010-08/AllSkyIm...,166.985608,20977901,117,245
12,2010/08/11,22:42:34,2.4769,000021278,2010-08.parquet,2010-08-11 22:42:34,/home/rainybyte/SomeSkyImages/2010-08/AllSkyIm...,158.146314,19867447,99,248
...,...,...,...,...,...,...,...,...,...,...,...
4,2026/03/25,05:40:08,32.0241,000422467,2026-03.parquet,2026-03-25 05:40:08,/home/rainybyte/SomeSkyImages/2026-03/AllSkyIm...,103.790141,13038844,51,221
5,2026/03/25,05:40:41,32.0241,000422468,2026-03.parquet,2026-03-25 05:40:41,/home/rainybyte/SomeSkyImages/2026-03/AllSkyIm...,103.978412,13062496,57,235
6,2026/03/25,05:41:34,36.3559,000422469,2026-03.parquet,2026-03-25 05:41:34,/home/rainybyte/SomeSkyImages/2026-03/AllSkyIm...,107.699698,13529990,56,232
7,2026/03/25,05:42:11,36.3559,000422470,2026-03.parquet,2026-03-25 05:42:11,/home/rainybyte/SomeSkyImages/2026-03/AllSkyIm...,107.371680,13488782,59,253
8,2026/03/25,05:42:49,36.3559,000422471,2026-03.parquet,2026-03-25 05:42:49,/home/rainybyte/SomeSkyImages/2026-03/AllSkyIm...,107.022416,13444905,53,248

In [12]:
from allsky.analysis import quick_exposure_linregress

quick_exposure_linregress(enriched_df, "image_mean")

array([-1.77254198e-03,  1.45761371e+03])

In [13]:
enriched_df["image_mean"] * enriched_df["exposure"]

8      439.965361
9      395.953227
10     404.690073
11     413.606653
12     391.712605
         ...
4     3323.785843
5     3329.815073
6     3915.519462
7     3903.594048
8     3890.896238
Length: 581805, dtype: float64